//! Module: wand-of-rust

#[crate_id = "wand_of_rust"];
#[crate_type = "dylib"];

#[desc = "ImageMagick's MagickWand bindings"];
#[license = "MIT"];

#[feature(globs)];

#[allow(dead_code)];

extern mod std;
use std::libc::{c_uint, size_t, c_double};

#[path="bindings.rs"]
mod bindings;

pub struct MagickWand {
  priv wand: *mut bindings::MagickWand
}

impl MagickWand {
  pub fn borrow(block: |&MagickWand|) {
    let wand = ~MagickWand { wand: unsafe { bindings::NewMagickWand() } };
    block(wand);
    unsafe { bindings::DestroyMagickWand(wand.wand); }
  }

  pub fn set_image_background_color(&self, pixel_wand: &PixelWand) {
    unsafe {
      bindings::MagickSetImageBackgroundColor(
        self.wand, 
        pixel_wand.wand as *std::libc::types::common::c95::c_void
      );
    }
  }

  pub fn read_image(&self, path: &str) {
    // TODO: Deal with error conditions somehow - maybe return a Result<Something,Error>?
    path.with_c_str(|buffer| {
      unsafe { bindings::MagickReadImage(self.wand, buffer) }
    });
  }

  pub fn get_image_width(&self) -> int {
    unsafe { bindings::MagickGetImageWidth(self.wand) as int }
  }

  pub fn get_image_height(&self) -> int {
    unsafe { bindings::MagickGetImageHeight(self.wand) as int }
  }

  pub fn resize_image(&self, width: int, height: int, filter: FilterType, arg: f64) {
    unsafe {
      bindings::MagickResizeImage(
        self.wand, width as size_t, height as size_t, 
        filter as c_uint, arg as c_double
      );
    }
  }

  pub fn extent_image(&self, width: int, height: int, x: int, y: int) {
    unsafe { 
      bindings::MagickExtentImage(
        self.wand, width as u64, height as u64, x as i64, y as i64
      ); 
    }
  }

  pub fn reset_iterator(&self) {
    // TODO: Again, deal with error conditions
    unsafe { bindings::MagickResetIterator(self.wand); }
  }

  pub fn each_image(&self, block: ||) {
    unsafe {
      while (bindings::MagickNextImage(self.wand) != bindings::MagickFalse) {
        // TODO: This counts as multiple calls
        block();
      }
    };
  }

  pub fn set_image_compression_quality(&self, quality: u64) {
    unsafe { bindings::MagickSetImageCompressionQuality(self.wand, quality); }
  }

  pub fn write_image(&self, path: &str) {
    path.with_c_str(|buffer| {
      unsafe { bindings::MagickWriteImage(self.wand, buffer); }
    })
  }

  pub fn write_images(&self, path: &str, adjoin: bool) {
    let magic_version = match adjoin {
      false => bindings::MagickFalse,
      true => bindings::MagickTrue
    };
    unsafe {
      path.with_c_str(|buffer| {
        bindings::MagickWriteImages(self.wand, buffer, magic_version);
      })
    }
  }
}

pub struct PixelWand {
  priv wand: *mut bindings::PixelWand
}

impl PixelWand {
  pub fn borrow(block: |&PixelWand|) {
    let wand = ~PixelWand { wand: unsafe { bindings::NewPixelWand() } };
    block(wand);
    unsafe { bindings::DestroyPixelWand(wand.wand); }
  }

  pub fn set_color(&self, color: ColorName) {
    color_to_str(color).with_c_str(|buffer| {
      unsafe { bindings::PixelSetColor(self.wand, buffer); }
    })
  }
}

pub fn MagickWandGenesis() {
  unsafe { bindings::MagickWandGenesis() }
}

pub fn MagickWandTerminus() {
  unsafe { bindings::MagickWandTerminus() }
}

pub enum FilterType {
  UndefinedFilter = 0,
  PointFilter = 1,
  BoxFilter = 2,
  TriangleFilter = 3,
  HermiteFilter = 4,
  HanningFilter = 5,
  HammingFilter = 6,
  BlackmanFilter = 7,
  GaussianFilter = 8,
  QuadraticFilter = 9,
  CubicFilter = 10,
  CatromFilter = 11,
  MitchellFilter = 12,
  JincFilter = 13,
  SincFilter = 14,
  SincFastFilter = 15,
  KaiserFilter = 16,
  WelshFilter = 17,
  ParzenFilter = 18,
  BohmanFilter = 19,
  BartlettFilter = 20,
  LagrangeFilter = 21,
  LanczosFilter = 22,
  LanczosSharpFilter = 23,
  Lanczos2Filter = 24,
  Lanczos2SharpFilter = 25,
  RobidouxFilter = 26,
  RobidouxSharpFilter = 27,
  CosineFilter = 28,
  SplineFilter = 29,
  LanczosRadiusFilter = 30,
  SentinelFilter = 31
}

pub enum ColorName {
  // Adapted from the list provided here:
  //  http://www.imagemagick.org/script/color.php#color_names
  AliceBlue,
  AntiqueWhite,
  AntiqueWhite1,
  AntiqueWhite2,
  AntiqueWhite3,
  AntiqueWhite4,
  Aqua,
  Aquamarine,
  Aquamarine1,
  Aquamarine2,
  Aquamarine3,
  Aquamarine4,
  Azure,
  Azure1,
  Azure2,
  Azure3,
  Azure4,
  Beige,
  Bisque,
  Bisque1,
  Bisque2,
  Bisque3,
  Bisque4,
  Black,
  BlanchedAlmond,
  Blue,
  Blue1,
  Blue2,
  Blue3,
  Blue4,
  BlueViolet,
  Brown,
  Brown1,
  Brown2,
  Brown3,
  Brown4,
  Burlywood,
  Burlywood1,
  Burlywood2,
  Burlywood3,
  Burlywood4,
  Cadet,
  CadetBlue,
  CadetBlue1,
  CadetBlue2,
  CadetBlue3,
  CadetBlue4,
  Chartreuse,
  Chartreuse1,
  Chartreuse2,
  Chartreuse3,
  Chartreuse4,
  Chocolate,
  Chocolate1,
  Chocolate2,
  Chocolate3,
  Chocolate4,
  Coral,
  Coral1,
  Coral2,
  Coral3,
  Coral4,
  CornflowerBlue,
  Cornsilk,
  Cornsilk1,
  Cornsilk2,
  Cornsilk3,
  Cornsilk4,
  Crimson,
  Cyan,
  Cyan1,
  Cyan2,
  Cyan3,
  Cyan4,
  DarkBlue,
  DarkCyan,
  DarkGoldenrod,
  DarkGoldenrod1,
  DarkGoldenrod2,
  DarkGoldenrod3,
  DarkGoldenrod4,
  DarkGray,
  DarkGreen,
  DarkGrey,
  DarkKhaki,
  DarkMagenta,
  DarkOliveGreen,
  DarkOliveGreen1,
  DarkOliveGreen2,
  DarkOliveGreen3,
  DarkOliveGreen4,
  DarkOrange,
  DarkOrange1,
  DarkOrange2,
  DarkOrange3,
  DarkOrange4,
  DarkOrchid,
  DarkOrchid1,
  DarkOrchid2,
  DarkOrchid3,
  DarkOrchid4,
  DarkRed,
  DarkSalmon,
  DarkSeaGreen,
  DarkSeaGreen1,
  DarkSeaGreen2,
  DarkSeaGreen3,
  DarkSeaGreen4,
  DarkSlateBlue,
  DarkSlateGray,
  DarkSlateGray1,
  DarkSlateGray2,
  DarkSlateGray3,
  DarkSlateGray4,
  DarkSlateGrey,
  DarkTurquoise,
  DarkViolet,
  DeepPink,
  DeepPink1,
  DeepPink2,
  DeepPink3,
  DeepPink4,
  DeepSkyBlue,
  DeepSkyBlue1,
  DeepSkyBlue2,
  DeepSkyBlue3,
  DeepSkyBlue4,
  DimGray,
  DimGrey,
  DodgerBlue,
  DodgerBlue1,
  DodgerBlue2,
  DodgerBlue3,
  DodgerBlue4,
  Firebrick,
  Firebrick1,
  Firebrick2,
  Firebrick3,
  Firebrick4,
  FloralWhite,
  ForestGreen,
  Fractal,
  Fuchsia,
  Gainsboro,
  GhostWhite,
  Gold,
  Gold1,
  Gold2,
  Gold3,
  Gold4,
  Goldenrod,
  Goldenrod1,
  Goldenrod2,
  Goldenrod3,
  Goldenrod4,
  Gray,
  Gray0,
  Gray1,
  Gray10,
  Gray100,
  Gray11,
  Gray12,
  Gray13,
  Gray14,
  Gray15,
  Gray16,
  Gray17,
  Gray18,
  Gray19,
  Gray2,
  Gray20,
  Gray21,
  Gray22,
  Gray23,
  Gray24,
  Gray25,
  Gray26,
  Gray27,
  Gray28,
  Gray29,
  Gray3,
  Gray30,
  Gray31,
  Gray32,
  Gray33,
  Gray34,
  Gray35,
  Gray36,
  Gray37,
  Gray38,
  Gray39,
  Gray4,
  Gray40,
  Gray41,
  Gray42,
  Gray43,
  Gray44,
  Gray45,
  Gray46,
  Gray47,
  Gray48,
  Gray49,
  Gray5,
  Gray50,
  Gray51,
  Gray52,
  Gray53,
  Gray54,
  Gray55,
  Gray56,
  Gray57,
  Gray58,
  Gray59,
  Gray6,
  Gray60,
  Gray61,
  Gray62,
  Gray63,
  Gray64,
  Gray65,
  Gray66,
  Gray67,
  Gray68,
  Gray69,
  Gray7,
  Gray70,
  Gray71,
  Gray72,
  Gray73,
  Gray74,
  Gray75,
  Gray76,
  Gray77,
  Gray78,
  Gray79,
  Gray8,
  Gray80,
  Gray81,
  Gray82,
  Gray83,
  Gray84,
  Gray85,
  Gray86,
  Gray87,
  Gray88,
  Gray89,
  Gray9,
  Gray90,
  Gray91,
  Gray92,
  Gray93,
  Gray94,
  Gray95,
  Gray96,
  Gray97,
  Gray98,
  Gray99,
  Green,
  Green1,
  Green2,
  Green3,
  Green4,
  GreenYellow,
  Grey0,
  Grey1,
  Grey10,
  Grey100,
  Grey11,
  Grey12,
  Grey13,
  Grey14,
  Grey15,
  Grey16,
  Grey17,
  Grey18,
  Grey19,
  Grey2,
  Grey20,
  Grey21,
  Grey22,
  Grey23,
  Grey24,
  Grey25,
  Grey26,
  Grey27,
  Grey28,
  Grey29,
  Grey3,
  Grey30,
  Grey31,
  Grey32,
  Grey33,
  Grey34,
  Grey35,
  Grey36,
  Grey37,
  Grey38,
  Grey39,
  Grey4,
  Grey40,
  Grey41,
  Grey42,
  Grey43,
  Grey44,
  Grey45,
  Grey46,
  Grey47,
  Grey48,
  Grey49,
  Grey5,
  Grey50,
  Grey51,
  Grey52,
  Grey53,
  Grey54,
  Grey55,
  Grey56,
  Grey57,
  Grey58,
  Grey59,
  Grey6,
  Grey60,
  Grey61,
  Grey62,
  Grey63,
  Grey64,
  Grey65,
  Grey66,
  Grey67,
  Grey68,
  Grey69,
  Grey7,
  Grey70,
  Grey71,
  Grey72,
  Grey73,
  Grey74,
  Grey75,
  Grey76,
  Grey77,
  Grey78,
  Grey79,
  Grey8,
  Grey80,
  Grey81,
  Grey82,
  Grey83,
  Grey84,
  Grey85,
  Grey86,
  Grey87,
  Grey88,
  Grey89,
  Grey9,
  Grey90,
  Grey91,
  Grey92,
  Grey93,
  Grey94,
  Grey95,
  Grey96,
  Grey97,
  Grey98,
  Grey99,
  Honeydew,
  Honeydew1,
  Honeydew2,
  Honeydew3,
  Honeydew4,
  HotPink,
  HotPink1,
  HotPink2,
  HotPink3,
  HotPink4,
  IndianRed,
  IndianRed1,
  IndianRed2,
  IndianRed3,
  IndianRed4,
  Indigo,
  Ivory,
  Ivory1,
  Ivory2,
  Ivory3,
  Ivory4,
  Khaki,
  Khaki1,
  Khaki2,
  Khaki3,
  Khaki4,
  Lavender,
  LavenderBlush,
  LavenderBlush1,
  LavenderBlush2,
  LavenderBlush3,
  LavenderBlush4,
  LawnGreen,
  LemonChiffon,
  LemonChiffon1,
  LemonChiffon2,
  LemonChiffon3,
  LemonChiffon4,
  LightBlue,
  LightBlue1,
  LightBlue2,
  LightBlue3,
  LightBlue4,
  LightCoral,
  LightCyan,
  LightCyan1,
  LightCyan2,
  LightCyan3,
  LightCyan4,
  LightGoldenrod,
  LightGoldenrod1,
  LightGoldenrod2,
  LightGoldenrod3,
  LightGoldenrod4,
  LightGoldenrodYellow,
  LightGray,
  LightGreen,
  LightGrey,
  LightPink,
  LightPink1,
  LightPink2,
  LightPink3,
  LightPink4,
  LightSalmon,
  LightSalmon1,
  LightSalmon2,
  LightSalmon3,
  LightSalmon4,
  LightSeaGreen,
  LightSkyBlue,
  LightSkyBlue1,
  LightSkyBlue2,
  LightSkyBlue3,
  LightSkyBlue4,
  LightSlateBlue,
  LightSlateGray,
  LightSlateGrey,
  LightSteelBlue,
  LightSteelBlue1,
  LightSteelBlue2,
  LightSteelBlue3,
  LightSteelBlue4,
  LightYellow,
  LightYellow1,
  LightYellow2,
  LightYellow3,
  LightYellow4,
  Lime,
  LimeGreen,
  Linen,
  Magenta,
  Magenta1,
  Magenta2,
  Magenta3,
  Magenta4,
  Maroon,
  Maroon1,
  Maroon2,
  Maroon3,
  Maroon4,
  MediumAquamarine,
  MediumBlue,
  MediumForestGreen,
  MediumGoldenRod,
  MediumOrchid,
  MediumOrchid1,
  MediumOrchid2,
  MediumOrchid3,
  MediumOrchid4,
  MediumPurple,
  MediumPurple1,
  MediumPurple2,
  MediumPurple3,
  MediumPurple4,
  MediumSeaGreen,
  MediumSlateBlue,
  MediumSpringGreen,
  MediumTurquoise,
  MediumVioletRed,
  MidnightBlue,
  MintCream,
  MistyRose,
  MistyRose1,
  MistyRose2,
  MistyRose3,
  MistyRose4,
  Moccasin,
  NavajoWhite,
  NavajoWhite1,
  NavajoWhite2,
  NavajoWhite3,
  NavajoWhite4,
  Navy,
  NavyBlue,
  OldLace,
  Olive,
  OliveDrab,
  OliveDrab1,
  OliveDrab2,
  OliveDrab3,
  OliveDrab4,
  Opaque,
  Orange,
  Orange1,
  Orange2,
  Orange3,
  Orange4,
  OrangeRed,
  OrangeRed1,
  OrangeRed2,
  OrangeRed3,
  OrangeRed4,
  Orchid,
  Orchid1,
  Orchid2,
  Orchid3,
  Orchid4,
  PaleGoldenrod,
  PaleGreen,
  PaleGreen1,
  PaleGreen2,
  PaleGreen3,
  PaleGreen4,
  PaleTurquoise,
  PaleTurquoise1,
  PaleTurquoise2,
  PaleTurquoise3,
  PaleTurquoise4,
  PaleVioletRed,
  PaleVioletRed1,
  PaleVioletRed2,
  PaleVioletRed3,
  PaleVioletRed4,
  PapayaWhip,
  PeachPuff,
  PeachPuff1,
  PeachPuff2,
  PeachPuff3,
  PeachPuff4,
  Peru,
  Pink,
  Pink1,
  Pink2,
  Pink3,
  Pink4,
  Plum,
  Plum1,
  Plum2,
  Plum3,
  Plum4,
  PowderBlue,
  Purple,
  Purple1,
  Purple2,
  Purple3,
  Purple4,
  Red,
  Red1,
  Red2,
  Red3,
  Red4,
  RosyBrown,
  RosyBrown1,
  RosyBrown2,
  RosyBrown3,
  RosyBrown4,
  RoyalBlue,
  RoyalBlue1,
  RoyalBlue2,
  RoyalBlue3,
  RoyalBlue4,
  SaddleBrown,
  Salmon,
  Salmon1,
  Salmon2,
  Salmon3,
  Salmon4,
  SandyBrown,
  SeaGreen,
  SeaGreen1,
  SeaGreen2,
  SeaGreen3,
  SeaGreen4,
  Seashell,
  Seashell1,
  Seashell2,
  Seashell3,
  Seashell4,
  Sienna,
  Sienna1,
  Sienna2,
  Sienna3,
  Sienna4,
  Silver,
  SkyBlue,
  SkyBlue1,
  SkyBlue2,
  SkyBlue3,
  SkyBlue4,
  SlateBlue,
  SlateBlue1,
  SlateBlue2,
  SlateBlue3,
  SlateBlue4,
  SlateGray,
  SlateGray1,
  SlateGray2,
  SlateGray3,
  SlateGray4,
  SlateGrey,
  Snow,
  Snow1,
  Snow2,
  Snow3,
  Snow4,
  SpringGreen,
  SpringGreen1,
  SpringGreen2,
  SpringGreen3,
  SpringGreen4,
  SteelBlue,
  SteelBlue1,
  SteelBlue2,
  SteelBlue3,
  SteelBlue4,
  Tan,
  Tan1,
  Tan2,
  Tan3,
  Tan4,
  Teal,
  Thistle,
  Thistle1,
  Thistle2,
  Thistle3,
  Thistle4,
  Tomato,
  Tomato1,
  Tomato2,
  Tomato3,
  Tomato4,
  Transparent,
  Turquoise,
  Turquoise1,
  Turquoise2,
  Turquoise3,
  Turquoise4,
  Violet,
  VioletRed,
  VioletRed1,
  VioletRed2,
  VioletRed3,
  VioletRed4,
  Wheat,
  Wheat1,
  Wheat2,
  Wheat3,
  Wheat4,
  White,
  WhiteSmoke,
  Yellow,
  Yellow1,
  Yellow2,
  Yellow3,
  Yellow4,
  YellowGreen,
  None
}

fn color_to_str(color: ColorName) -> &str {
  match color {
    Snow => "snow",
    Snow1 => "snow1",
    Snow2 => "snow2",
    RosyBrown1 => "RosyBrown1",
    RosyBrown2 => "RosyBrown2",
    Snow3 => "snow3",
    LightCoral => "LightCoral",
    IndianRed1 => "IndianRed1",
    RosyBrown3 => "RosyBrown3",
    IndianRed2 => "IndianRed2",
    RosyBrown => "RosyBrown",
    Brown1 => "brown1",
    Firebrick1 => "firebrick1",
    Brown2 => "brown2",
    IndianRed => "IndianRed",
    IndianRed3 => "IndianRed3",
    Firebrick2 => "firebrick2",
    Snow4 => "snow4",
    Brown3 => "brown3",
    Red => "red",
    Red1 => "red1",
    RosyBrown4 => "RosyBrown4",
    Firebrick3 => "firebrick3",
    Red2 => "red2",
    Firebrick => "firebrick",
    Brown => "brown",
    Red3 => "red3",
    IndianRed4 => "IndianRed4",
    Brown4 => "brown4",
    Firebrick4 => "firebrick4",
    DarkRed => "DarkRed",
    Red4 => "red4",
    Maroon => "maroon",
    LightPink1 => "LightPink1",
    LightPink3 => "LightPink3",
    LightPink4 => "LightPink4",
    LightPink2 => "LightPink2",
    LightPink => "LightPink",
    Pink => "pink",
    Crimson => "crimson",
    Pink1 => "pink1",
    Pink2 => "pink2",
    Pink3 => "pink3",
    Pink4 => "pink4",
    PaleVioletRed4 => "PaleVioletRed4",
    PaleVioletRed => "PaleVioletRed",
    PaleVioletRed2 => "PaleVioletRed2",
    PaleVioletRed1 => "PaleVioletRed1",
    PaleVioletRed3 => "PaleVioletRed3",
    LavenderBlush => "LavenderBlush",
    LavenderBlush1 => "LavenderBlush1",
    LavenderBlush3 => "LavenderBlush3",
    LavenderBlush2 => "LavenderBlush2",
    LavenderBlush4 => "LavenderBlush4",
    HotPink3 => "HotPink3",
    VioletRed3 => "VioletRed3",
    VioletRed1 => "VioletRed1",
    VioletRed2 => "VioletRed2",
    VioletRed4 => "VioletRed4",
    HotPink2 => "HotPink2",
    HotPink1 => "HotPink1",
    HotPink4 => "HotPink4",
    HotPink => "HotPink",
    DeepPink => "DeepPink",
    DeepPink1 => "DeepPink1",
    DeepPink2 => "DeepPink2",
    DeepPink3 => "DeepPink3",
    DeepPink4 => "DeepPink4",
    Maroon1 => "maroon1",
    Maroon2 => "maroon2",
    Maroon3 => "maroon3",
    Maroon4 => "maroon4",
    MediumVioletRed => "MediumVioletRed",
    VioletRed => "VioletRed",
    Orchid2 => "orchid2",
    Orchid => "orchid",
    Orchid1 => "orchid1",
    Orchid3 => "orchid3",
    Orchid4 => "orchid4",
    Thistle1 => "thistle1",
    Thistle2 => "thistle2",
    Plum1 => "plum1",
    Plum2 => "plum2",
    Thistle => "thistle",
    Thistle3 => "thistle3",
    Plum => "plum",
    Violet => "violet",
    Plum3 => "plum3",
    Thistle4 => "thistle4",
    Fuchsia => "fuchsia",
    Magenta => "magenta",
    Magenta1 => "magenta1",
    Plum4 => "plum4",
    Magenta2 => "magenta2",
    Magenta3 => "magenta3",
    DarkMagenta => "DarkMagenta",
    Magenta4 => "magenta4",
    MediumOrchid => "MediumOrchid",
    MediumOrchid1 => "MediumOrchid1",
    MediumOrchid2 => "MediumOrchid2",
    MediumOrchid3 => "MediumOrchid3",
    MediumOrchid4 => "MediumOrchid4",
    DarkViolet => "DarkViolet",
    DarkOrchid => "DarkOrchid",
    DarkOrchid1 => "DarkOrchid1",
    DarkOrchid3 => "DarkOrchid3",
    DarkOrchid2 => "DarkOrchid2",
    DarkOrchid4 => "DarkOrchid4",
    Purple => "purple",
    Indigo => "indigo",
    BlueViolet => "BlueViolet",
    Purple2 => "purple2",
    Purple3 => "purple3",
    Purple4 => "purple4",
    Purple1 => "purple1",
    MediumPurple => "MediumPurple",
    MediumPurple1 => "MediumPurple1",
    MediumPurple2 => "MediumPurple2",
    MediumPurple3 => "MediumPurple3",
    MediumPurple4 => "MediumPurple4",
    DarkSlateBlue => "DarkSlateBlue",
    LightSlateBlue => "LightSlateBlue",
    MediumSlateBlue => "MediumSlateBlue",
    SlateBlue => "SlateBlue",
    SlateBlue1 => "SlateBlue1",
    SlateBlue2 => "SlateBlue2",
    SlateBlue3 => "SlateBlue3",
    SlateBlue4 => "SlateBlue4",
    GhostWhite => "GhostWhite",
    Lavender => "lavender",
    Blue => "blue",
    Blue1 => "blue1",
    Blue2 => "blue2",
    Blue3 => "blue3",
    MediumBlue => "MediumBlue",
    Blue4 => "blue4",
    DarkBlue => "DarkBlue",
    MidnightBlue => "MidnightBlue",
    Navy => "navy",
    NavyBlue => "NavyBlue",
    RoyalBlue => "RoyalBlue",
    RoyalBlue1 => "RoyalBlue1",
    RoyalBlue2 => "RoyalBlue2",
    RoyalBlue3 => "RoyalBlue3",
    RoyalBlue4 => "RoyalBlue4",
    CornflowerBlue => "CornflowerBlue",
    LightSteelBlue => "LightSteelBlue",
    LightSteelBlue1 => "LightSteelBlue1",
    LightSteelBlue2 => "LightSteelBlue2",
    LightSteelBlue3 => "LightSteelBlue3",
    LightSteelBlue4 => "LightSteelBlue4",
    SlateGray4 => "SlateGray4",
    SlateGray1 => "SlateGray1",
    SlateGray2 => "SlateGray2",
    SlateGray3 => "SlateGray3",
    LightSlateGray => "LightSlateGray",
    LightSlateGrey => "LightSlateGrey",
    SlateGray => "SlateGray",
    SlateGrey => "SlateGrey",
    DodgerBlue => "DodgerBlue",
    DodgerBlue1 => "DodgerBlue1",
    DodgerBlue2 => "DodgerBlue2",
    DodgerBlue4 => "DodgerBlue4",
    DodgerBlue3 => "DodgerBlue3",
    AliceBlue => "AliceBlue",
    SteelBlue4 => "SteelBlue4",
    SteelBlue => "SteelBlue",
    SteelBlue1 => "SteelBlue1",
    SteelBlue2 => "SteelBlue2",
    SteelBlue3 => "SteelBlue3",
    SkyBlue4 => "SkyBlue4",
    SkyBlue1 => "SkyBlue1",
    SkyBlue2 => "SkyBlue2",
    SkyBlue3 => "SkyBlue3",
    LightSkyBlue => "LightSkyBlue",
    LightSkyBlue4 => "LightSkyBlue4",
    LightSkyBlue1 => "LightSkyBlue1",
    LightSkyBlue2 => "LightSkyBlue2",
    LightSkyBlue3 => "LightSkyBlue3",
    SkyBlue => "SkyBlue",
    LightBlue3 => "LightBlue3",
    DeepSkyBlue => "DeepSkyBlue",
    DeepSkyBlue1 => "DeepSkyBlue1",
    DeepSkyBlue2 => "DeepSkyBlue2",
    DeepSkyBlue4 => "DeepSkyBlue4",
    DeepSkyBlue3 => "DeepSkyBlue3",
    LightBlue1 => "LightBlue1",
    LightBlue2 => "LightBlue2",
    LightBlue => "LightBlue",
    LightBlue4 => "LightBlue4",
    PowderBlue => "PowderBlue",
    CadetBlue1 => "CadetBlue1",
    CadetBlue2 => "CadetBlue2",
    CadetBlue3 => "CadetBlue3",
    CadetBlue4 => "CadetBlue4",
    Turquoise1 => "turquoise1",
    Turquoise2 => "turquoise2",
    Turquoise3 => "turquoise3",
    Turquoise4 => "turquoise4",
    Cadet => "blue",
    CadetBlue => "CadetBlue",
    DarkTurquoise => "DarkTurquoise",
    Azure => "azure",
    Azure1 => "azure1",
    LightCyan => "LightCyan",
    LightCyan1 => "LightCyan1",
    Azure2 => "azure2",
    LightCyan2 => "LightCyan2",
    PaleTurquoise1 => "PaleTurquoise1",
    PaleTurquoise => "PaleTurquoise",
    PaleTurquoise2 => "PaleTurquoise2",
    DarkSlateGray1 => "DarkSlateGray1",
    Azure3 => "azure3",
    LightCyan3 => "LightCyan3",
    DarkSlateGray2 => "DarkSlateGray2",
    PaleTurquoise3 => "PaleTurquoise3",
    DarkSlateGray3 => "DarkSlateGray3",
    Azure4 => "azure4",
    LightCyan4 => "LightCyan4",
    Aqua => "aqua",
    Cyan => "cyan",
    Cyan1 => "cyan1",
    PaleTurquoise4 => "PaleTurquoise4",
    Cyan2 => "cyan2",
    DarkSlateGray4 => "DarkSlateGray4",
    Cyan3 => "cyan3",
    Cyan4 => "cyan4",
    DarkCyan => "DarkCyan",
    Teal => "teal",
    DarkSlateGray => "DarkSlateGray",
    DarkSlateGrey => "DarkSlateGrey",
    MediumTurquoise => "MediumTurquoise",
    LightSeaGreen => "LightSeaGreen",
    Turquoise => "turquoise",
    Aquamarine4 => "aquamarine4",
    Aquamarine => "aquamarine",
    Aquamarine1 => "aquamarine1",
    Aquamarine2 => "aquamarine2",
    Aquamarine3 => "aquamarine3",
    MediumAquamarine => "MediumAquamarine",
    MediumSpringGreen => "MediumSpringGreen",
    MintCream => "MintCream",
    SpringGreen => "SpringGreen",
    SpringGreen1 => "SpringGreen1",
    SpringGreen2 => "SpringGreen2",
    SpringGreen3 => "SpringGreen3",
    SpringGreen4 => "SpringGreen4",
    MediumSeaGreen => "MediumSeaGreen",
    SeaGreen => "SeaGreen",
    SeaGreen3 => "SeaGreen3",
    SeaGreen1 => "SeaGreen1",
    SeaGreen4 => "SeaGreen4",
    SeaGreen2 => "SeaGreen2",
    MediumForestGreen => "MediumForestGreen",
    Honeydew => "honeydew",
    Honeydew1 => "honeydew1",
    Honeydew2 => "honeydew2",
    DarkSeaGreen1 => "DarkSeaGreen1",
    DarkSeaGreen2 => "DarkSeaGreen2",
    PaleGreen1 => "PaleGreen1",
    PaleGreen => "PaleGreen",
    Honeydew3 => "honeydew3",
    LightGreen => "LightGreen",
    PaleGreen2 => "PaleGreen2",
    DarkSeaGreen3 => "DarkSeaGreen3",
    DarkSeaGreen => "DarkSeaGreen",
    PaleGreen3 => "PaleGreen3",
    Honeydew4 => "honeydew4",
    Green1 => "green1",
    Lime => "lime",
    LimeGreen => "LimeGreen",
    DarkSeaGreen4 => "DarkSeaGreen4",
    Green2 => "green2",
    PaleGreen4 => "PaleGreen4",
    Green3 => "green3",
    ForestGreen => "ForestGreen",
    Green4 => "green4",
    Green => "green",
    DarkGreen => "DarkGreen",
    LawnGreen => "LawnGreen",
    Chartreuse => "chartreuse",
    Chartreuse1 => "chartreuse1",
    Chartreuse2 => "chartreuse2",
    Chartreuse3 => "chartreuse3",
    Chartreuse4 => "chartreuse4",
    GreenYellow => "GreenYellow",
    DarkOliveGreen3 => "DarkOliveGreen3",
    DarkOliveGreen1 => "DarkOliveGreen1",
    DarkOliveGreen2 => "DarkOliveGreen2",
    DarkOliveGreen4 => "DarkOliveGreen4",
    DarkOliveGreen => "DarkOliveGreen",
    OliveDrab => "OliveDrab",
    OliveDrab1 => "OliveDrab1",
    OliveDrab2 => "OliveDrab2",
    OliveDrab3 => "OliveDrab3",
    YellowGreen => "YellowGreen",
    OliveDrab4 => "OliveDrab4",
    Ivory => "ivory",
    Ivory1 => "ivory1",
    LightYellow => "LightYellow",
    LightYellow1 => "LightYellow1",
    Beige => "beige",
    Ivory2 => "ivory2",
    LightGoldenrodYellow => "LightGoldenrodYellow",
    LightYellow2 => "LightYellow2",
    Ivory3 => "ivory3",
    LightYellow3 => "LightYellow3",
    Ivory4 => "ivory4",
    LightYellow4 => "LightYellow4",
    Yellow => "yellow",
    Yellow1 => "yellow1",
    Yellow2 => "yellow2",
    Yellow3 => "yellow3",
    Yellow4 => "yellow4",
    Olive => "olive",
    DarkKhaki => "DarkKhaki",
    Khaki2 => "khaki2",
    LemonChiffon4 => "LemonChiffon4",
    Khaki1 => "khaki1",
    Khaki3 => "khaki3",
    Khaki4 => "khaki4",
    PaleGoldenrod => "PaleGoldenrod",
    LemonChiffon => "LemonChiffon",
    LemonChiffon1 => "LemonChiffon1",
    Khaki => "khaki",
    LemonChiffon3 => "LemonChiffon3",
    LemonChiffon2 => "LemonChiffon2",
    MediumGoldenRod => "MediumGoldenRod",
    Cornsilk4 => "cornsilk4",
    Gold => "gold",
    Gold1 => "gold1",
    Gold2 => "gold2",
    Gold3 => "gold3",
    Gold4 => "gold4",
    LightGoldenrod => "LightGoldenrod",
    LightGoldenrod4 => "LightGoldenrod4",
    LightGoldenrod1 => "LightGoldenrod1",
    LightGoldenrod3 => "LightGoldenrod3",
    LightGoldenrod2 => "LightGoldenrod2",
    Cornsilk3 => "cornsilk3",
    Cornsilk2 => "cornsilk2",
    Cornsilk => "cornsilk",
    Cornsilk1 => "cornsilk1",
    Goldenrod => "goldenrod",
    Goldenrod1 => "goldenrod1",
    Goldenrod2 => "goldenrod2",
    Goldenrod3 => "goldenrod3",
    Goldenrod4 => "goldenrod4",
    DarkGoldenrod => "DarkGoldenrod",
    DarkGoldenrod1 => "DarkGoldenrod1",
    DarkGoldenrod2 => "DarkGoldenrod2",
    DarkGoldenrod3 => "DarkGoldenrod3",
    DarkGoldenrod4 => "DarkGoldenrod4",
    FloralWhite => "FloralWhite",
    Wheat2 => "wheat2",
    OldLace => "OldLace",
    Wheat => "wheat",
    Wheat1 => "wheat1",
    Wheat3 => "wheat3",
    Orange => "orange",
    Orange1 => "orange1",
    Orange2 => "orange2",
    Orange3 => "orange3",
    Orange4 => "orange4",
    Wheat4 => "wheat4",
    Moccasin => "moccasin",
    PapayaWhip => "PapayaWhip",
    NavajoWhite3 => "NavajoWhite3",
    BlanchedAlmond => "BlanchedAlmond",
    NavajoWhite => "NavajoWhite",
    NavajoWhite1 => "NavajoWhite1",
    NavajoWhite2 => "NavajoWhite2",
    NavajoWhite4 => "NavajoWhite4",
    AntiqueWhite4 => "AntiqueWhite4",
    AntiqueWhite => "AntiqueWhite",
    Tan => "tan",
    Bisque4 => "bisque4",
    Burlywood => "burlywood",
    AntiqueWhite2 => "AntiqueWhite2",
    Burlywood1 => "burlywood1",
    Burlywood3 => "burlywood3",
    Burlywood2 => "burlywood2",
    AntiqueWhite1 => "AntiqueWhite1",
    Burlywood4 => "burlywood4",
    AntiqueWhite3 => "AntiqueWhite3",
    DarkOrange => "DarkOrange",
    Bisque2 => "bisque2",
    Bisque => "bisque",
    Bisque1 => "bisque1",
    Bisque3 => "bisque3",
    DarkOrange1 => "DarkOrange1",
    Linen => "linen",
    DarkOrange2 => "DarkOrange2",
    DarkOrange3 => "DarkOrange3",
    DarkOrange4 => "DarkOrange4",
    Peru => "peru",
    Tan1 => "tan1",
    Tan2 => "tan2",
    Tan3 => "tan3",
    Tan4 => "tan4",
    PeachPuff => "PeachPuff",
    PeachPuff1 => "PeachPuff1",
    PeachPuff4 => "PeachPuff4",
    PeachPuff2 => "PeachPuff2",
    PeachPuff3 => "PeachPuff3",
    SandyBrown => "SandyBrown",
    Seashell4 => "seashell4",
    Seashell2 => "seashell2",
    Seashell3 => "seashell3",
    Chocolate => "chocolate",
    Chocolate1 => "chocolate1",
    Chocolate2 => "chocolate2",
    Chocolate3 => "chocolate3",
    Chocolate4 => "chocolate4",
    SaddleBrown => "SaddleBrown",
    Seashell => "seashell",
    Seashell1 => "seashell1",
    Sienna4 => "sienna4",
    Sienna => "sienna",
    Sienna1 => "sienna1",
    Sienna2 => "sienna2",
    Sienna3 => "sienna3",
    LightSalmon3 => "LightSalmon3",
    LightSalmon => "LightSalmon",
    LightSalmon1 => "LightSalmon1",
    LightSalmon4 => "LightSalmon4",
    LightSalmon2 => "LightSalmon2",
    Coral => "coral",
    OrangeRed => "OrangeRed",
    OrangeRed1 => "OrangeRed1",
    OrangeRed2 => "OrangeRed2",
    OrangeRed3 => "OrangeRed3",
    OrangeRed4 => "OrangeRed4",
    DarkSalmon => "DarkSalmon",
    Salmon1 => "salmon1",
    Salmon2 => "salmon2",
    Salmon3 => "salmon3",
    Salmon4 => "salmon4",
    Coral1 => "coral1",
    Coral2 => "coral2",
    Coral3 => "coral3",
    Coral4 => "coral4",
    Tomato4 => "tomato4",
    Tomato => "tomato",
    Tomato1 => "tomato1",
    Tomato2 => "tomato2",
    Tomato3 => "tomato3",
    MistyRose4 => "MistyRose4",
    MistyRose2 => "MistyRose2",
    MistyRose => "MistyRose",
    MistyRose1 => "MistyRose1",
    Salmon => "salmon",
    MistyRose3 => "MistyRose3",
    White => "white",
    Gray100 => "gray100",
    Grey100 => "grey100",
    Gray99 => "gray99",
    Grey99 => "grey99",
    Gray98 => "gray98",
    Grey98 => "grey98",
    Gray97 => "gray97",
    Grey97 => "grey97",
    Gray96 => "gray96",
    Grey96 => "grey96",
    WhiteSmoke => "WhiteSmoke",
    Gray95 => "gray95",
    Grey95 => "grey95",
    Gray94 => "gray94",
    Grey94 => "grey94",
    Gray93 => "gray93",
    Grey93 => "grey93",
    Gray92 => "gray92",
    Grey92 => "grey92",
    Gray91 => "gray91",
    Grey91 => "grey91",
    Gray90 => "gray90",
    Grey90 => "grey90",
    Gray89 => "gray89",
    Grey89 => "grey89",
    Gray88 => "gray88",
    Grey88 => "grey88",
    Gray87 => "gray87",
    Grey87 => "grey87",
    Gainsboro => "gainsboro",
    Gray86 => "gray86",
    Grey86 => "grey86",
    Gray85 => "gray85",
    Grey85 => "grey85",
    Gray84 => "gray84",
    Grey84 => "grey84",
    Gray83 => "gray83",
    Grey83 => "grey83",
    LightGray => "LightGray",
    LightGrey => "LightGrey",
    Gray82 => "gray82",
    Grey82 => "grey82",
    Gray81 => "gray81",
    Grey81 => "grey81",
    Gray80 => "gray80",
    Grey80 => "grey80",
    Gray79 => "gray79",
    Grey79 => "grey79",
    Gray78 => "gray78",
    Grey78 => "grey78",
    Gray77 => "gray77",
    Grey77 => "grey77",
    Gray76 => "gray76",
    Grey76 => "grey76",
    Silver => "silver",
    Gray75 => "gray75",
    Grey75 => "grey75",
    Gray74 => "gray74",
    Grey74 => "grey74",
    Gray73 => "gray73",
    Grey73 => "grey73",
    Gray72 => "gray72",
    Grey72 => "grey72",
    Gray71 => "gray71",
    Grey71 => "grey71",
    Gray70 => "gray70",
    Grey70 => "grey70",
    Gray69 => "gray69",
    Grey69 => "grey69",
    Gray68 => "gray68",
    Grey68 => "grey68",
    Gray67 => "gray67",
    Grey67 => "grey67",
    DarkGray => "DarkGray",
    DarkGrey => "DarkGrey",
    Gray66 => "gray66",
    Grey66 => "grey66",
    Gray65 => "gray65",
    Grey65 => "grey65",
    Gray64 => "gray64",
    Grey64 => "grey64",
    Gray63 => "gray63",
    Grey63 => "grey63",
    Gray62 => "gray62",
    Grey62 => "grey62",
    Gray61 => "gray61",
    Grey61 => "grey61",
    Gray60 => "gray60",
    Grey60 => "grey60",
    Gray59 => "gray59",
    Grey59 => "grey59",
    Gray58 => "gray58",
    Grey58 => "grey58",
    Gray57 => "gray57",
    Grey57 => "grey57",
    Gray56 => "gray56",
    Grey56 => "grey56",
    Gray55 => "gray55",
    Grey55 => "grey55",
    Gray54 => "gray54",
    Grey54 => "grey54",
    Gray53 => "gray53",
    Grey53 => "grey53",
    Gray52 => "gray52",
    Grey52 => "grey52",
    Gray51 => "gray51",
    Grey51 => "grey51",
    Fractal => "fractal",
    Gray50 => "gray50",
    Grey50 => "grey50",
    Gray => "gray",
    Gray49 => "gray49",
    Grey49 => "grey49",
    Gray48 => "gray48",
    Grey48 => "grey48",
    Gray47 => "gray47",
    Grey47 => "grey47",
    Gray46 => "gray46",
    Grey46 => "grey46",
    Gray45 => "gray45",
    Grey45 => "grey45",
    Gray44 => "gray44",
    Grey44 => "grey44",
    Gray43 => "gray43",
    Grey43 => "grey43",
    Gray42 => "gray42",
    Grey42 => "grey42",
    DimGray => "DimGray",
    DimGrey => "DimGrey",
    Gray41 => "gray41",
    Grey41 => "grey41",
    Gray40 => "gray40",
    Grey40 => "grey40",
    Gray39 => "gray39",
    Grey39 => "grey39",
    Gray38 => "gray38",
    Grey38 => "grey38",
    Gray37 => "gray37",
    Grey37 => "grey37",
    Gray36 => "gray36",
    Grey36 => "grey36",
    Gray35 => "gray35",
    Grey35 => "grey35",
    Gray34 => "gray34",
    Grey34 => "grey34",
    Gray33 => "gray33",
    Grey33 => "grey33",
    Gray32 => "gray32",
    Grey32 => "grey32",
    Gray31 => "gray31",
    Grey31 => "grey31",
    Gray30 => "gray30",
    Grey30 => "grey30",
    Gray29 => "gray29",
    Grey29 => "grey29",
    Gray28 => "gray28",
    Grey28 => "grey28",
    Gray27 => "gray27",
    Grey27 => "grey27",
    Gray26 => "gray26",
    Grey26 => "grey26",
    Gray25 => "gray25",
    Grey25 => "grey25",
    Gray24 => "gray24",
    Grey24 => "grey24",
    Gray23 => "gray23",
    Grey23 => "grey23",
    Gray22 => "gray22",
    Grey22 => "grey22",
    Gray21 => "gray21",
    Grey21 => "grey21",
    Gray20 => "gray20",
    Grey20 => "grey20",
    Gray19 => "gray19",
    Grey19 => "grey19",
    Gray18 => "gray18",
    Grey18 => "grey18",
    Gray17 => "gray17",
    Grey17 => "grey17",
    Gray16 => "gray16",
    Grey16 => "grey16",
    Gray15 => "gray15",
    Grey15 => "grey15",
    Gray14 => "gray14",
    Grey14 => "grey14",
    Gray13 => "gray13",
    Grey13 => "grey13",
    Gray12 => "gray12",
    Grey12 => "grey12",
    Gray11 => "gray11",
    Grey11 => "grey11",
    Gray10 => "gray10",
    Grey10 => "grey10",
    Gray9 => "gray9",
    Grey9 => "grey9",
    Gray8 => "gray8",
    Grey8 => "grey8",
    Gray7 => "gray7",
    Grey7 => "grey7",
    Gray6 => "gray6",
    Grey6 => "grey6",
    Gray5 => "gray5",
    Grey5 => "grey5",
    Gray4 => "gray4",
    Grey4 => "grey4",
    Gray3 => "gray3",
    Grey3 => "grey3",
    Gray2 => "gray2",
    Grey2 => "grey2",
    Gray1 => "gray1",
    Grey1 => "grey1",
    Black => "black",
    Gray0 => "gray0",
    Grey0 => "grey0",
    Opaque => "opaque",
    Transparent => "transparent",
    _ => "None"
  }
}
